import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/lib/theme-provider";
import { TanstackProvider } from "@/components/providers/tanstack-provider";
import { NextAuthProvider } from "@/components/providers/nextauth-provider";
import { ConditionalSidebar } from "@/components/conditional-sidebar";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthProvider>
            <TanstackProvider>
              <div className="min-h-screen flex flex-col">
                <div className="flex-1">
                  <ConditionalSidebar>{children}</ConditionalSidebar>
                </div>
                <Footer />
              </div>
            </TanstackProvider>
          </NextAuthProvider>
          <Toaster
            richColors
            position="top-right"
            visibleToasts={5}
            duration={3000}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
